### ISSUE TITLE
training failing with "cuda_device": 0

### ISSUE THREAD

**Issue by sidbrahma** [allenai/allennlp-as-a-library-example#19] opened 2018-12-12 23:28 UTC
When I set "cuda_device": 0, the training is failing with the following error
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #4 'tensor1'

Do I need to set the cuda flag somewhere else too?

**Comment by matt-gardner** [comment] 2018-12-13 15:58
We're going to need more detail than this in order to help you.

**Comment by jyori112** [comment] 2018-12-16 07:59
I got the same error and struggling to fix it.

I simply replaced `trainer.cuda_device` in `experiments/venue_classifier.json` to 0 and run
```
pipenv run allennlp train experiments/venue_classifier.json -s ./output --include-package my_library -f
```

Here is the error message I got (I replaced my username with `user`)
```
Traceback (most recent call last):
  File "/home/user/pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/allennlp/commands/train.py", line 142, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/allennlp/commands/train.py", line 351, in train_model
    metrics = trainer.train()
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/allennlp/training/trainer.py", line 755, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/allennlp/training/trainer.py", line 525, in _train_epoch
    self.optimizer.step()
  File "/home/user/.local/share/virtualenvs/allennlp-DZJHh1Ke/lib/python3.7/site-packages/torch/optim/adagrad.py", line 92, in step
    state['sum'].addcmul_(1, grad, grad)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #4 'tensor1'
```
(I am using pipenv)

I checked that in `forward` function of the model (`my_library/models/academic_paper_classifier.py`), all inputs are on GPU and computed loss is also on the GPU.

**Comment by matt-gardner** [comment] 2018-12-17 22:49
This repo assumes an older version of allennlp that didn't have this issue.  The issue is with adagrad, and was a regression in 0.7.2 that is now fixed on master.  See https://github.com/allenai/allennlp/issues/2189.

**Closed as completed by matt-gardner** 2018-12-17 22:49 UTC
